development:
  bucket: mylunchin.com-dev
  access_key_id: AKIAIIAHBGCHRK2DXVXA
  secret_access_key: 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

test:
  bucket: mylunchin.com-tst
  access_key_id: AKIAIIAHBGCHRK2DXVXA
  secret_access_key: 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

production:
  bucket: mylunchin.com-prd
  access_key_id: AKIAIIAHBGCHRK2DXVXA
  secret_access_key: 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
